# Generated by Django 4.1.1 on 2022-09-21 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='data')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome')),
                ('localizacao', models.URLField(blank=True, verbose_name='localizacao')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('foto', models.URLField(blank=True, verbose_name='foto')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='data')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='data')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.combustivel')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posto')),
            ],
        ),
    ]
