# Generated by Django 4.1.1 on 2022-09-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustíveis'},
        ),
        migrations.AlterModelOptions(
            name='posto',
            options={'verbose_name': 'Posto', 'verbose_name_plural': 'Postos'},
        ),
        migrations.AlterModelOptions(
            name='preco',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
        migrations.RenameField(
            model_name='posto',
            old_name='administrador',
            new_name='adm',
        ),
        migrations.RenameField(
            model_name='preco',
            old_name='administrador',
            new_name='adm',
        ),
    ]
