# Generated by Django 4.1.1 on 2022-09-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_combustivel_options_alter_posto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='combustivel', to='core.combustivel'),
        ),
    ]
