# Generated by Django 4.1.1 on 2022-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_preco_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='bandeira',
            field=models.CharField(blank=True, max_length=50, verbose_name='bandeira'),
        ),
    ]
